# Generated by Django 6.0.7 on 2026-07-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the author.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book.', max_length=250)),
                ('publication_year', models.IntegerField(help_text='The year the book was published.')),
                ('author', models.ForeignKey(help_text='The author of the book.', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who registered/owns this book record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
